on: ["push", "pull_request"]
name: Test

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ["8.6.5"]
        cabal: ["3.0"]
        cache-version: ["v4"]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - uses: mstksg/setup-stack@v1
      - name: test
        run: stack test
